{
 "title": "PTP Clock Overview Simple",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({job=\"SPG9000\"},name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$host", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "host" },
  {
   "title": "Front Panel LED Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spg9000_led_state{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spg9000_gnss_status{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spg9000_ptp_state{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spg9000_num_alerts{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spg9000_num_faults{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GNSS Constellation",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spg9000_satellites_in_view{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spg9000_satellites_in_fix{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    { "expression": "$in_view - $in_fix", "type": "math" }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 1, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spg9000_gnss_figure_of_merit{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GNSS Signal Quality",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 7, "y": 3 },
   "targets": [
    {
     "expr": "spg9000_signal_quality{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load (%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 4, "x": 11, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "spg9000_cpu_load_1min{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Vital Stats",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spg9000_memory_used{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spg9000_memory_total{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spg9000_disk_used{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "spg9000_disk_total{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    },
    { "expression": "$mem_used / $mem_total", "type": "math" },
    { "expression": "$disk_used / $disk_total", "type": "math" }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 17, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "spg9000_uptime{job=\"SPG9000\", name=\"$host\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}